(() => {
const BUILD='20260929a', ADV_KEY='movie30_adv_filter_v66', PRESET_KEY='movie30_filter_presets_v66', HISTORY_KEY='movie30_change_history_v66', AUDIT_KEY='movie30_genre_audit_v66';
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v)), uniq=a=>[...new Set((a||[]).filter(Boolean))];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch(_){return d}}, write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};

const css=document.createElement('style');css.textContent=`
.v66-adv{display:none;background:#0d1117;border:1px solid var(--line);border-radius:12px;padding:10px;margin:-2px 0 10px}.v66-adv.open{display:block}
.v66-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.v66-lbl{font-size:9px;color:var(--muted);font-weight:700;margin-bottom:4px}.v66-range{display:grid;grid-template-columns:1fr auto 1fr;gap:5px;align-items:center}.v66-range em{font-size:10px;color:var(--muted);font-style:normal}
.v66-chips{display:flex;gap:5px;flex-wrap:wrap}.v66-chip{border:1px solid var(--line);background:#10151c;color:#aeb7c4;border-radius:999px;padding:5px 8px;font-size:9.5px}.v66-chip.inc{border-color:#3e8d5a;color:#c8f3d5}.v66-chip.exc{border-color:#8d4747;color:#ffc5c5}
.v66-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.v66-actions .field{flex:1;min-width:150px}.v66-badge{display:none;font-size:9px;color:#a9e8bd;border:1px solid #315c40;border-radius:999px;padding:3px 7px}.v66-badge.on{display:inline-block}
.rank-card.v66-focus{outline:2px solid var(--accent);box-shadow:0 0 0 4px rgba(67,209,125,.13)}.v66-pos{grid-column:1/-1;display:grid;grid-template-columns:1fr 1fr 1.35fr;gap:5px;padding-top:5px;border-top:1px solid rgba(255,255,255,.06)}.v66-pos button{border:1px solid var(--line);background:#0c1117;color:#dbe3ec;border-radius:7px;padding:6px 5px;font-size:9.5px}.v66-pos .back{color:#a9e8bd;border-color:#315c40}
.v66-detail{background:#0b0f14;border:1px solid var(--line);border-radius:12px;padding:10px;margin:9px 0}.v66-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.v66-stat{background:#121923;border-radius:9px;padding:7px;text-align:center}.v66-stat strong{display:block;font-size:15px}.v66-stat span{font-size:8px;color:var(--muted)}.v66-nei{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:7px}.v66-nei>div{background:#111720;border:1px solid var(--line);border-radius:8px;padding:7px;font-size:9px;color:var(--muted)}.v66-nei b{display:block;color:#e3e9f0;font-size:10.5px;margin-top:2px}.v66-note{width:100%;min-height:70px;background:#0b0f14;border:1px solid var(--line);border-radius:8px;color:#e6ebf1;padding:8px}
.v66-bg{display:none;position:fixed;inset:0;background:rgba(0,0,0,.72);z-index:260;align-items:flex-end;justify-content:center}.v66-bg.open{display:flex}.v66-sheet{width:min(820px,100%);max-height:92vh;overflow:auto;background:#10151c;border:1px solid #2a323d;border-radius:20px 20px 0 0;padding:12px 10px calc(16px + env(safe-area-inset-bottom))}.v66-head{position:sticky;top:-12px;z-index:2;background:#10151c;border-bottom:1px solid var(--line);padding:6px 2px 9px}.v66-title{font-size:18px;font-weight:900}.v66-sub{font-size:9.5px;color:var(--muted);margin-top:3px}.v66-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:7px;align-items:center;background:#141b24;border:1px solid var(--line);border-radius:10px;padding:8px;margin-top:6px}.v66-row strong{font-size:10.5px}.v66-row small{display:block;font-size:8.5px;color:var(--muted);margin-top:2px}.v66-mini{border:1px solid var(--line);background:#0c1117;color:#dbe3ec;border-radius:7px;padding:5px 7px;font-size:9px}.v66-good{border-color:#315c40;color:#a9e8bd}.v66-hold{border-color:#77652f;color:#f4d978}.v66-bad{border-color:#703b3b;color:#ffbcbc}.v66-empty{font-size:10px;color:var(--muted);padding:14px;text-align:center}.v66-anom{margin-top:12px;border-top:1px solid var(--line);padding-top:9px}
@media(max-width:650px){.v66-grid{grid-template-columns:1fr}.v66-stats{grid-template-columns:repeat(2,1fr)}.v66-pos{grid-template-columns:1fr 1fr}.v66-pos .back{grid-column:1/-1}}
`;document.head.appendChild(css);

// history
const MAPS=['assignments','starOverrides','exactScores','rankOrder','titleOverrides','categoryOverrides','mediaTypeOverrides','genreOverrides','originOverrides','formatOverrides','runtimeOverrides','letterboxdMeta'];
const snap=()=>{const o={};for(const k of MAPS)o[k]=clone(state[k]||{});o.customFilms=clone(state.customFilms||[]);return o};
let shadow=snap(), applying=false, hist=read(HISTORY_KEY,[]);if(!Array.isArray(hist))hist=[];
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function diff(a,b){const z=[];for(const f of MAPS){const x=a[f]||{},y=b[f]||{},ks=new Set([...Object.keys(x),...Object.keys(y)]);for(const k of ks){const hx=Object.prototype.hasOwnProperty.call(x,k),hy=Object.prototype.hasOwnProperty.call(y,k);if(hx===hy&&same(x[k],y[k]))continue;z.push({f,k,hx,b:hx?clone(x[k]):null})}}if(!same(a.customFilms,b.customFilms))z.push({f:'customFilms',whole:1,b:clone(a.customFilms)});return z}
const fl={exactScores:'点数',rankOrder:'順位',genreOverrides:'ジャンル',runtimeOverrides:'上映時間',titleOverrides:'タイトル',letterboxdMeta:'メモ',starOverrides:'星',mediaTypeOverrides:'種別',originOverrides:'制作区分',formatOverrides:'形式',customFilms:'作品追加・削除'};
function htitle(c){const ids=uniq(c.filter(x=>x.k&&!/^\d+$/.test(x.k)).map(x=>x.k)),fs=uniq(c.map(x=>fl[x.f]||x.f));let t=ids.length===1?(()=>{try{return displayTitle(filmById(ids[0]))}catch(_){return ids[0]}})()+'：':'';return t+fs.slice(0,3).join('・')+'変更'}
const oldSave=save;save=function(...a){const now=snap();if(!applying){const c=diff(shadow,now);if(c.length){hist.unshift({id:Date.now()+'-'+Math.random().toString(36).slice(2,6),at:Date.now(),t:htitle(c),c});hist=hist.slice(0,50);write(HISTORY_KEY,hist);renderHist()}}const r=oldSave(...a);shadow=now;return r};
function undo(h){if(!h)return;applying=true;try{for(const c of [...h.c].reverse()){if(c.whole){state[c.f]=clone(c.b);continue}state[c.f]=state[c.f]||{};if(c.hx)state[c.f][c.k]=clone(c.b);else delete state[c.f][c.k]}oldSave(false);shadow=snap()}finally{applying=false}hist=hist.filter(x=>x.id!==h.id);write(HISTORY_KEY,hist);render();renderHist();toast('変更を元に戻しました')}

// advanced filters
const def=()=>({include:[],exclude:[],yearMin:'',yearMax:'',runtimeMin:'',runtimeMax:'',scoreMin:'',scoreMax:''});let adv={...def(),...(read(ADV_KEY,{})||{})};adv.include=uniq(adv.include);adv.exclude=uniq(adv.exclude).filter(x=>!adv.include.includes(x));let presets=read(PRESET_KEY,{});if(!presets||typeof presets!=='object'||Array.isArray(presets))presets={};
const genres=()=>{const s=new Set();const q=document.getElementById('genreFilterRank');if(q)for(const o of q.options)if(o.value)s.add(o.value);for(const a of Object.values(state.genreOverrides||{}))for(const g of(Array.isArray(a)?a:[]))s.add(g);return [...s].sort((a,b)=>a.localeCompare(b,'ja'))};
const fg=f=>uniq(state.genreOverrides?.[f?.id]||[]), rt=f=>{const n=Number(state.runtimeOverrides?.[f?.id]??f?.runtime);return Number.isFinite(n)&&n>0?n:null}, nb=v=>v!==''&&Number.isFinite(Number(v))?Number(v):null;
const advOn=()=>adv.include.length||adv.exclude.length||['yearMin','yearMax','runtimeMin','runtimeMax','scoreMin','scoreMax'].some(k=>String(adv[k]??'')!=='');
function pass(f){const g=fg(f),y=Number(f.year),r=rt(f),s=effectiveScore(f),a=nb(adv.yearMin),b=nb(adv.yearMax),c=nb(adv.runtimeMin),d=nb(adv.runtimeMax),e=nb(adv.scoreMin),h=nb(adv.scoreMax);if(adv.include.some(x=>!g.includes(x))||adv.exclude.some(x=>g.includes(x)))return false;if(a!=null&&(!Number.isFinite(y)||y<a))return false;if(b!=null&&(!Number.isFinite(y)||y>b))return false;if(c!=null&&(r==null||r<c))return false;if(d!=null&&(r==null||r>d))return false;if(e!=null&&(s==null||s<e))return false;if(h!=null&&(s==null||s>h))return false;return true}
const filterIds=['searchRank','categoryFilterRank','genreFilterRank','mediaFilterRank','originFilterRank','formatFilterRank','decadeFilterRank','runtimeFilterRank'];
const filtered=()=>!!advOn()||filterIds.some(id=>String(document.getElementById(id)?.value||'').trim());
function cap(){const o={adv:clone(adv)};for(const id of filterIds)o[id]=document.getElementById(id)?.value||'';return o}
function applyCap(o){if(!o)return;for(const id of filterIds){const e=document.getElementById(id);if(e)e.value=o[id]||''}adv={...def(),...(clone(o.adv)||{})};write(ADV_KEY,adv);drawAdv();renderRank()}
function clearFilters(){for(const id of filterIds){const e=document.getElementById(id);if(e)e.value=''}adv=def();write(ADV_KEY,adv);drawAdv()}

const tools=document.querySelector('#page-rank .tools');if(tools&&!document.getElementById('advToggle66')){const badge=document.createElement('span');badge.id='advBadge66';badge.className='v66-badge';badge.textContent='詳細絞込中';tools.appendChild(badge);for(const [id,t] of [['advToggle66','詳細絞込'],['auditOpen66','ジャンル監査'],['histOpen66','履歴'],['undo66','↶ Undo']]){const b=document.createElement('button');b.id=id;b.className='btn';b.type='button';b.textContent=t;tools.appendChild(b)}}
let ab=document.getElementById('advBox66');if(!ab&&tools){ab=document.createElement('div');ab.id='advBox66';ab.className='v66-adv';tools.insertAdjacentElement('afterend',ab)}
function drawAdv(){if(!ab)return;const gs=genres();ab.innerHTML=`<div class="v66-grid">
<div><div class="v66-lbl">公開年（範囲）</div><div class="v66-range"><input class="field" id="y166" type="number" placeholder="1980" value="${esc(adv.yearMin||'')}"><em>〜</em><input class="field" id="y266" type="number" placeholder="2026" value="${esc(adv.yearMax||'')}"></div></div>
<div><div class="v66-lbl">上映時間・分（範囲）</div><div class="v66-range"><input class="field" id="r166" type="number" placeholder="最短" value="${esc(adv.runtimeMin||'')}"><em>〜</em><input class="field" id="r266" type="number" placeholder="最長" value="${esc(adv.runtimeMax||'')}"></div></div>
<div><div class="v66-lbl">点数（範囲）</div><div class="v66-range"><input class="field" id="s166" type="number" placeholder="最低" value="${esc(adv.scoreMin||'')}"><em>〜</em><input class="field" id="s266" type="number" placeholder="最高" value="${esc(adv.scoreMax||'')}"></div></div></div>
<div class="v66-lbl" style="margin-top:9px">含むジャンル（複数指定はAND）</div><div class="v66-chips">${gs.map(g=>`<button type="button" class="v66-chip${adv.include.includes(g)?' inc':''}" data-inc="${encodeURIComponent(g)}">${esc(g)}</button>`).join('')}</div>
<div class="v66-lbl" style="margin-top:9px">除外ジャンル</div><div class="v66-chips">${gs.map(g=>`<button type="button" class="v66-chip${adv.exclude.includes(g)?' exc':''}" data-exc="${encodeURIComponent(g)}">${esc(g)}</button>`).join('')}</div>
<div class="v66-actions"><select class="field" id="preset66"><option value="">保存した条件…</option>${Object.keys(presets).sort().map(n=>`<option value="${encodeURIComponent(n)}">${esc(n)}</option>`).join('')}</select><button class="btn" id="savePreset66">条件保存</button><button class="btn" id="delPreset66">保存条件削除</button><button class="btn" id="clearAdv66">詳細条件クリア</button></div>`;
const bi=(id,k)=>{const e=document.getElementById(id);if(e)e.oninput=()=>{adv[k]=e.value;write(ADV_KEY,adv);renderRank()}};bi('y166','yearMin');bi('y266','yearMax');bi('r166','runtimeMin');bi('r266','runtimeMax');bi('s166','scoreMin');bi('s266','scoreMax');
ab.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>{const g=decodeURIComponent(b.dataset.inc),s=new Set(adv.include);s.has(g)?s.delete(g):s.add(g);adv.include=[...s];adv.exclude=adv.exclude.filter(x=>x!==g);write(ADV_KEY,adv);drawAdv();renderRank()});ab.querySelectorAll('[data-exc]').forEach(b=>b.onclick=()=>{const g=decodeURIComponent(b.dataset.exc),s=new Set(adv.exclude);s.has(g)?s.delete(g):s.add(g);adv.exclude=[...s];adv.include=adv.include.filter(x=>x!==g);write(ADV_KEY,adv);drawAdv();renderRank()});
document.getElementById('clearAdv66').onclick=()=>{adv=def();write(ADV_KEY,adv);drawAdv();renderRank()};document.getElementById('savePreset66').onclick=()=>{const n=(prompt('保存する絞り込み条件の名前')||'').trim();if(!n)return;presets[n]=cap();write(PRESET_KEY,presets);drawAdv();toast('条件を保存しました')};document.getElementById('preset66').onchange=e=>{const n=decodeURIComponent(e.target.value||'');if(n&&presets[n])applyCap(presets[n])};document.getElementById('delPreset66').onclick=()=>{const n=decodeURIComponent(document.getElementById('preset66')?.value||'');if(n&&presets[n]){delete presets[n];write(PRESET_KEY,presets);drawAdv()}};document.getElementById('advBadge66')?.classList.toggle('on',!!advOn())}
drawAdv();document.getElementById('advToggle66')?.addEventListener('click',()=>ab?.classList.toggle('open'));

let backFilters=null, focusId=null;
function swap(id,d){const f=filmById(id),sc=f&&effectiveScore(f);if(sc==null)return;const a=rankSorted(allFilms().filter(x=>effectiveScore(x)===sc),sc),i=a.findIndex(x=>x.id===id),j=i+d;if(j<0||j>=a.length){toast('この点数内では端です。点数をまたぐ移動は≡ドラッグで');return}[a[i],a[j]]=[a[j],a[i]];state.rankOrder[String(sc)]=a.map(x=>x.id);save();renderRank();jumpFocus(id)}
function posTools(id){const c=document.querySelector(`.rank-card[data-id="${encodeURIComponent(id)}"]`);if(!c)return;document.querySelectorAll('.v66-pos').forEach(x=>x.remove());document.querySelectorAll('.rank-card.v66-focus').forEach(x=>x.classList.remove('v66-focus'));c.classList.add('v66-focus');const d=document.createElement('div');d.className='v66-pos';d.innerHTML=`<button data-sw="-1">↑ 前と入替</button><button data-sw="1">↓ 次と入替</button>${backFilters?'<button class="back" data-back="1">← 検索・絞込結果へ戻る</button>':'<span></span>'}`;c.appendChild(d);d.querySelectorAll('[data-sw]').forEach(b=>b.onclick=e=>{e.stopPropagation();swap(id,Number(b.dataset.sw))});d.querySelector('[data-back]')?.addEventListener('click',e=>{e.stopPropagation();const s=backFilters;backFilters=null;applyCap(s);setTimeout(()=>document.querySelector(`.rank-card[data-id="${encodeURIComponent(id)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),50)})}
function jumpFocus(id){focusId=id;requestAnimationFrame(()=>{const c=document.querySelector(`.rank-card[data-id="${encodeURIComponent(id)}"]`);if(c){c.scrollIntoView({behavior:'auto',block:'center'});posTools(id)}focusId=null})}
function jumpGlobal(id){if(filtered())backFilters=cap();clearFilters();renderRank();jumpFocus(id);toast('全体順位の位置へ移動しました')}
function decorate(){const f=filtered();for(const c of document.querySelectorAll('#rankRoot .rank-card')){const id=decodeURIComponent(c.dataset.id||''),h=c.querySelector('.drag-handle');if(!h)continue;h.disabled=false;if(f){h.textContent='↕';h.title='全体順位の位置へ';h.onpointerdown=e=>{e.preventDefault();e.stopPropagation();jumpGlobal(id)}}else{h.textContent='≡';h.title='ドラッグで順位変更';h.onpointerdown=startDrag}}document.getElementById('advBadge66')?.classList.toggle('on',!!advOn());if(focusId)posTools(focusId)}
const rr=renderRank;renderRank=function(){rr();if(advOn()){document.querySelectorAll('#rankRoot .rank-card').forEach(c=>{const f=filmById(decodeURIComponent(c.dataset.id||''));if(f&&!pass(f))c.remove()});for(const bin of document.querySelectorAll('#rankRoot .score-bin')){const n=bin.querySelectorAll('.rank-card').length,sm=bin.querySelector('.score-label small');if(sm)sm.textContent=n+'本';if(!n)bin.remove()}for(const s of document.querySelectorAll('#rankRoot .rank-star'))if(!s.querySelector('.rank-card'))s.remove()}decorate()};

// richer detail in existing edit sheet
function rankInfo(f){const scores=uniq(allFilms().map(effectiveScore).filter(x=>x!=null).map(Number)).sort((a,b)=>b-a),flat=[];for(const s of scores)flat.push(...rankSorted(allFilms().filter(x=>Number(effectiveScore(x))===s),s));const i=flat.findIndex(x=>x.id===f.id),sc=effectiveScore(f),same=sc==null?[]:rankSorted(allFilms().filter(x=>Number(effectiveScore(x))===Number(sc)),Number(sc)),j=same.findIndex(x=>x.id===f.id);return {all:i<0?null:i+1,total:flat.length,same:j<0?null:j+1,st:same.length,up:i>0?flat[i-1]:null,down:i>=0&&i<flat.length-1?flat[i+1]:null}}
function detail(f){const meta=document.getElementById('sheetMeta');if(!meta)return;let b=document.getElementById('detail66');if(!b){b=document.createElement('div');b.id='detail66';b.className='v66-detail';meta.insertAdjacentElement('afterend',b)}const x=rankInfo(f),m=state.letterboxdMeta?.[f.id]||{},sc=effectiveScore(f),gs=fg(f);b.innerHTML=`<div class="v66-stats"><div class="v66-stat"><strong>${sc??'—'}</strong><span>点数</span></div><div class="v66-stat"><strong>${x.all?x.all+'位':'—'}</strong><span>全体 ${x.total}本</span></div><div class="v66-stat"><strong>${x.same?x.same+'位':'—'}</strong><span>${sc??'—'}点内 ${x.st}本</span></div><div class="v66-stat"><strong>${rt(f)?rt(f)+'分':'—'}</strong><span>上映時間</span></div></div><div class="v66-nei"><div>ひとつ上<b>${x.up?esc(displayTitle(x.up)):'—'}</b></div><div>ひとつ下<b>${x.down?esc(displayTitle(x.down)):'—'}</b></div></div><div class="tip">公開年：${esc(f.year||'不明')} ／ ジャンル：${gs.length?gs.map(esc).join('・'):'未設定'}${m.reportedWatchedDate?'<br>鑑賞日：'+esc(m.reportedWatchedDate):''}${m.addedDate?' ／ Letterboxd追加：'+esc(m.addedDate):''}</div><div class="v66-lbl">一言メモ</div><textarea id="note66" class="v66-note" placeholder="この点数にした理由、印象、再鑑賞メモなど">${esc(m.note||'')}</textarea><div class="v66-actions"><button class="btn" id="detailJump66">全体順位の位置へ</button></div>`;document.getElementById('note66').onchange=e=>{state.letterboxdMeta=state.letterboxdMeta||{};state.letterboxdMeta[f.id]={...(state.letterboxdMeta[f.id]||{}),note:e.target.value};save();toast('メモを保存しました')};document.getElementById('detailJump66').onclick=()=>{const id=f.id;closeSheet();jumpGlobal(id)}}
const os=openSheet;openSheet=function(id){os(id);const f=filmById(id);if(f)detail(f)};

// genre audit
let ast=read(AUDIT_KEY,{});if(!ast||typeof ast!=='object')ast={};let ag='',only=false;
const bg=document.createElement('div');bg.id='auditBg66';bg.className='v66-bg';bg.innerHTML=`<div class="v66-sheet"><div class="v66-head"><div style="display:flex;justify-content:space-between;gap:8px"><div><div class="v66-title">ジャンル監査</div><div class="v66-sub">残す／保留／削除で高速確認。シリーズ内のタグ差分も候補表示。</div></div><button class="btn" id="auditClose66">閉じる</button></div><div class="tools" style="margin-bottom:0"><select class="field" id="auditGenre66"></select><label class="checkline" style="margin:0"><input type="checkbox" id="auditOnly66">未確認のみ</label></div></div><div id="auditBody66"></div></div>`;document.body.appendChild(bg);
function family(f){const x=titleInfo(f)||{},t=[displayTitle(f),x.englishTitle,x.originalTitle].filter(Boolean).join(' ').toLowerCase(),p=[['star wars',/star wars|スター.?ウォーズ/],['harry potter',/harry potter|ハリー.?ポッター/],['spider-man',/spider.?man|スパイダーマン/],['matrix',/\bmatrix\b|マトリックス/],['jurassic',/jurassic|ジュラシック/],['hunger games',/hunger games|ハンガー.?ゲーム/],['toy story',/toy story|トイ.?ストーリー/],['men in black',/men in black|メン.?イン.?ブラック/],['ant-man',/ant.?man|アントマン/],['avengers',/avengers|アベンジャーズ/],['thor',/\bthor\b|マイティ.?ソー/],['john wick',/john wick|ジョン.?ウィック/],['godfather',/godfather|ゴッドファーザー/],['back to future',/back to the future|バック.?トゥ.?ザ.?フューチャー/],['conan',/detective conan|名探偵コナン|コナン /],['doraemon',/doraemon|ドラえもん/]];for(const [k,r] of p)if(r.test(t))return k;return''}
function drawAudit(){const sel=document.getElementById('auditGenre66'),body=document.getElementById('auditBody66');if(!sel||!body)return;const gs=genres();if(!ag||!gs.includes(ag))ag=gs[0]||'';sel.innerHTML=gs.map(g=>`<option value="${encodeURIComponent(g)}"${g===ag?' selected':''}>${esc(g)}</option>`).join('');ast[ag]=ast[ag]||{};const st=ast[ag],all=allFilms(),tag=all.filter(f=>fg(f).includes(ag)).sort((a,b)=>(effectiveScore(b)??-1)-(effectiveScore(a)??-1)),show=only?tag.filter(f=>!st[f.id]):tag,groups=new Map;for(const f of all){const k=family(f);if(k){if(!groups.has(k))groups.set(k,[]);groups.get(k).push(f)}}const an=[];for(const [k,a]of groups){if(a.length<2)continue;const y=a.filter(f=>fg(f).includes(ag)),n=a.filter(f=>!fg(f).includes(ag));if(y.length&&n.length)for(const f of n)an.push({k,f,y:y.length,t:a.length})}body.innerHTML=`<div class="tip">${tag.length}本に付与 ／ 確認済み ${tag.filter(f=>st[f.id]).length}/${tag.length} ／ シリーズ差分候補 ${an.length}</div>${show.length?show.map(f=>`<div class="v66-row"><div><strong>${esc(displayTitle(f))}</strong><small>${f.year||''}${effectiveScore(f)!=null?' · '+effectiveScore(f)+'点':''}${st[f.id]?' · '+(st[f.id]==='keep'?'残す確認済み':'保留中'):''}</small></div><div><button class="v66-mini v66-good" data-k="${encodeURIComponent(f.id)}">残す</button> <button class="v66-mini v66-hold" data-h="${encodeURIComponent(f.id)}">保留</button> <button class="v66-mini v66-bad" data-r="${encodeURIComponent(f.id)}">削除</button></div></div>`).join(''):'<div class="v66-empty">対象なし</div>'}<div class="v66-anom"><b>シリーズ内の差分候補</b>${an.length?an.slice(0,30).map(a=>`<div class="v66-row"><div><strong>${esc(displayTitle(a.f))}</strong><small>${esc(a.k)}：${a.y}/${a.t}作には ${esc(ag)} あり</small></div><button class="v66-mini v66-good" data-a="${encodeURIComponent(a.f.id)}">＋付与</button></div>`).join(''):'<div class="v66-empty">目立つ差分なし</div>'}</div>`;body.querySelectorAll('[data-k]').forEach(b=>b.onclick=()=>{st[decodeURIComponent(b.dataset.k)]='keep';write(AUDIT_KEY,ast);drawAudit()});body.querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>{st[decodeURIComponent(b.dataset.h)]='hold';write(AUDIT_KEY,ast);drawAudit()});body.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{const id=decodeURIComponent(b.dataset.r),f=filmById(id);state.genreOverrides[id]=fg(f).filter(g=>g!==ag);delete st[id];write(AUDIT_KEY,ast);save();render();drawAudit()});body.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{const id=decodeURIComponent(b.dataset.a),f=filmById(id);state.genreOverrides[id]=uniq([...fg(f),ag]);save();render();drawAudit()});sel.onchange=e=>{ag=decodeURIComponent(e.target.value);drawAudit()};const q=document.getElementById('auditOnly66');q.checked=only;q.onchange=()=>{only=q.checked;drawAudit()}}
document.getElementById('auditOpen66').onclick=()=>{ag=document.getElementById('genreFilterRank')?.value||ag||genres()[0]||'';drawAudit();bg.classList.add('open')};document.getElementById('auditClose66').onclick=()=>bg.classList.remove('open');bg.onclick=e=>{if(e.target===bg)bg.classList.remove('open')};

// history sheet
const hb=document.createElement('div');hb.id='histBg66';hb.className='v66-bg';hb.innerHTML=`<div class="v66-sheet"><div class="v66-head" style="display:flex;justify-content:space-between"><div><div class="v66-title">変更履歴</div><div class="v66-sub">直近50件。各変更だけ個別にUndoできます。</div></div><button class="btn" id="histClose66">閉じる</button></div><div id="histBody66"></div></div>`;document.body.appendChild(hb);
function renderHist(){const b=document.getElementById('histBody66');if(!b)return;b.innerHTML=hist.length?hist.map(h=>`<div class="v66-row"><div><strong>${esc(h.t||'変更')}</strong><small>${new Date(h.at).toLocaleString('ja-JP')} · ${h.c.length}項目</small></div><button class="v66-mini v66-bad" data-u="${h.id}">この変更を戻す</button></div>`).join(''):'<div class="v66-empty">まだ履歴はありません。</div>';b.querySelectorAll('[data-u]').forEach(x=>x.onclick=()=>undo(hist.find(h=>h.id===x.dataset.u)));const u=document.getElementById('undo66');if(u)u.disabled=!hist.length}
document.getElementById('histOpen66').onclick=()=>{renderHist();hb.classList.add('open')};document.getElementById('histClose66').onclick=()=>hb.classList.remove('open');hb.onclick=e=>{if(e.target===hb)hb.classList.remove('open')};document.getElementById('undo66').onclick=()=>hist[0]&&undo(hist[0]);renderHist();

// preserve current filters' own handlers but make sure the new handle behavior is refreshed.
for(const id of filterIds.filter(x=>x!=='searchRank')){const e=document.getElementById(id);if(!e)continue;const o=e.onchange;e.onchange=x=>{if(typeof o==='function')o.call(e,x);else renderRank();setTimeout(decorate,0)}}const sr=document.getElementById('searchRank');if(sr){const o=sr.oninput;sr.oninput=x=>{if(typeof o==='function')o.call(sr,x);else renderRank();setTimeout(decorate,0)}}
renderRank();const marker=document.getElementById('movie30BuildV29');if(marker)marker.textContent='app build '+BUILD;
})();